### ISSUE TITLE
ToDo ~ Ideas ~ Problems

### ISSUE THREAD

**Issue by MaicolAntali** [MaicolAntali/BarattoManager#42]
## Problemi 
- [x] Persistenza dei meet. _Se i meet subiscono un update i dati non sono persistenti. Questo è un problema sia per i Trade che per le statistiche del configuratore_ 
- [x] #43
- [x] Persistenza dei trade _I trade quando sono hanno articoli in stato `CLOSE_OFFERT` non devono essere cancellati/aggiornati servono per le statistiche del configuratore_ + _È coretto che i trade che su cui non viene fatta nessun azione (quindi scadono) vengano cancellati? problema legato alle statistiche_
- [x] ‼️ Verifica degli articoli. _Alcuni articoli dell'utente che ha fatto il login sono presenti nello store._
- [x] ‼️ `History` ha smesso di funzionare
- [x] Store no background update _Verificare se è iscritto all'evento, se si, identificare il problema_
- [x] #45
- [x] #44
- [x] Sistemare UI Trade
- [x] Azione `accetta`
- [x] Azione `accetta e riprogramma`
- [x] UIs configuratore
- [x] List meet vuota, mostrare errore
- [x] Tree si chiude quando i daemon fanno update 
- [x] Jmenu, a volte, non riconoscono i nodi
- [x] Verificare che gli articoli che possono essere scambiati non abbiano già trade in corso.
- [x] 5️⃣ I manager sono classi singleton, quindi non possono essere distrutte, come facciamo l'update?
- [x] 5️⃣ Se esistono già delle impostazioni, e il configuratore ne carica di nuove tramite JSON, cosa succede?

## Refactoring 
- [x] `CancelOffer.java` 
- [x] Implementare la nuova factory come gestore eventi in tutte le UI 
- [x] SelectMeetDatePanel classe duplicata. 
- [x] Tree estrarre un metodo per generare i log.
- [ ] Invertire atrributo bool del Meet

## Altro
- [x] #40 
- [x] Problema legato ai daemon thread.  _Se i dati vengono aggiornati da uno dei due tread e l'utente sta lavorando su quell'articolo cosa succede?_

## Bassa priorità
- [ ] Astrazione dei bottoni del configuratore + fix try/catch
- [ ] Assert
- [x] Nome articolo può essere vuoto
- [x] Vengono mostrati i campi non obbligatori, nelle offerte cancellate (anche se non compilati)
- [ ] Username, fare un `.trim()`
- [x] Quando viene creato un meet la prima cosa che viene controllata è l'orario e poi i campi. Meglio fare il contrario
- [x] Aggiunta di filtri durante la creazione dei meet. Non è più possibile creare meet vuoti.

## Seconda parte
- [ ] home configuratore, load json dividere

**Comment by Shubho10** [comment]
### Piccoli problemi

**messaggio d'errore sbagliato configura categorie**
- [ ]  Configura categorie - creazione nuovo campo vuoto - "il nome della sotto-categoria non valido" -> campo non valido
- [ ]  Configura categorie - creazione nuova sotto-categoria con descrizione vuota - "il nome della sotto-categoria non valido"  -> nome e descrizione non valida
- [ ] Configura categorie - creazione nuova categoria vuota - "il nome o la descrizione della categoria non é valido" 
- [ ] queste ultime tre di potrebbero generalizzare ???


**messaggio d'errore sbagliato configura meet**
- [ ] sono da rivedere i messaggi d'errore perchè sono un po' in disordine.


**Dubbi**
- [ ] perchè se inserisco alcuni campi vuoti(non quelli dell'orario) nella creazione del meet mi dice che non è possibile fare il parse della riga ?
- [ ] i meet che esistono gia non vengono creari e viene anche mostrato anche il popup, ma quelli che non estistono gia devono essere creati ?
