### ISSUE TITLE
Trade, gestione domanda/risposta

### ISSUE THREAD

**Issue by MaicolAntali** [MaicolAntali/BarattoManager#45]
_la UI deve capire chi è il creatore dello scambio in modo tale che posso mostrare un qualcosa di differente. Oltre al fatto che serve implementare un controllo sulle operazione di accetta. il creatore NON può accettare la sua offerta da solo. Quindi serve un sistema che capisca in che punto si trovi e quale dei due attori coinvolti deve rispondere._ 

## ToDo
- [x] Aggiungere alla classe Trade i parametro `log` _(guardare classe `Article` stessa implementazione di log)_
- [x] Definire getter e setter per `log` 

---
- [x] Dentro il package di Trade _(`com.barattOManager.model.trade`)_ creare una nuova classe chiamata `Answer`
- [x] Aggiungere a questa classe un attributo chiamato `waitingUserAnswer`,
- [x] Definire un costruttore
- [x] Definire getter per questo attributo
- [x] Aggiungere la nuova classe ad Article
